#!/bin/bash
cd
if [ $(id -u) != 0 ]
then
echo "Execute o script como root"
exit
fi
echo -e "\033[1;30mInstalando...\033[0m"
mkdir /etc/VpsPackdir 2>/dev/null
mkdir /etc/VpsPackdir/limite 2>/dev/null
mkdir /etc/VpsPackdir/senha 2>/dev/null
rm -rf /bin/sql3 2>/dev/null
wget -o /dev/null -O- https://github.com/Tomnet2001/VPSPACK-MOD/blob/master/VPSPACK%20mod/sq3 > /bin/sq3
chmod +x /bin/sq3
rm -rf /bin/dropb 2>/dev/null
wget -o /dev/null -O- https://github.com/Tomnet2001/VPSPACK-MOD/blob/master/VPSPACK%20mod/dropb > /bin/dropb
chmod +x /bin/dropb
rm -rf /bin/crearusuario 2>/dev/null
wget -o /dev/null -O- https://github.com/Tomnet2001/VPSPACK-MOD/blob/master/VPSPACK%20mod/crearusuario > /bin/crearusuario
chmod +x /bin/crearusuario
rm -rf /bin/eliminarusuario 2>/dev/null
wget -o /dev/null -O- https://github.com/Tomnet2001/VPSPACK-MOD/blob/master/VPSPACK%20mod/eliminarusuario > /bin/eliminarusuario
chmod +x /bin/eliminarusuario
rm -rf /bin/redefinirusuario 2>/dev/null
wget -o /dev/null -O- https://github.com/Tomnet2001/VPSPACK-MOD/blob/master/VPSPACK%20mod/redefinirusuario > /bin/redefinirusuario
chmod +x /bin/redefinirusuario
rm -rf /bin/menu 2>/dev/null
wget -o /dev/null -O- https://github.com/Tomnet2001/VPSPACK-MOD/blob/master/VPSPACK%20mod/menu > /bin/menu
chmod +x /bin/menu
rm -rf /bin/speedtest.py 2>/dev/null
wget -o /dev/null -O- https://github.com/Tomnet2001/VPSPACK-MOD/blob/master/VPSPACK%20mod/speedtest.py > /bin/speedtest.py
chmod +x /bin/speedtest.py
clear
echo -e "\033[1;32mInstalacao concluida\n\033[1;30mExecute:"
echo -e "\n\033[1;32mvpspack \033[1;30mMenu com opcoes"
echo -e "\033[1;32mcriarusuario \033[1;30mCriar usuario com data e limite"
echo -e "\033[1;32mdeletarusuario \033[1;30mDeletar usuario ou apenas desconectar"
echo -e "\033[1;32mredefinirusuario \033[1;30mAlterar data, senha, etc, de um usuario"
echo -e "\033[1;32mlimite \033[1;30mLimite de logins simultaneos\033[0m"
rm -rf install
