#!/bin/bash
read -p "Cual es el nombre del usuario para redefinir: " namer
 if cat /etc/passwd |grep $namer: > /dev/null
 then
 echo " "
 else
 clear
 echo "Usuario $namer no existe."
 exit
 fi
clear
echo -e "\033[1;33m¿Qué quieres restablecer? ?\033[1;30m
1) Numero de logins.
2) Dato de expiracion.
3) Cambiar contraseña de usuario"
read -p "Opcion: " option
if [ $option -eq 1 ]; then
read -p "Cual es el nuevo limite de logins: " liml
limite $namer $liml
exit 0
fi

if [ $option -eq 2 ]; then
echo "Cual es el nueva fecha : formato AAAA/MM/DD"
read -p ": " date
chage -E $date $namer 2> /dev/null
echo -e "\033[1;31mUsuario $namer Fecha: $date\033[0m"
exit
fi
if [ $option -eq 3 ]
then
read -p "Cual es la nueva contraseña para $namer: " senha
(echo "$senha" ; echo "$senha" ) |passwd $namer > /dev/null 2>/dev/null
echo "$senha" > /etc/VpsPackdir/senha/$namer
echo "Nueva contraseña aplicada."
exit
fi
